### ISSUE TITLE
各種Bot、Pluginの紹介ページを書く

### ISSUE THREAD

**Issue by raa0121** [akechi/web#1]
書く（ももんがさんが

**Comment by supermomonga** [comment]
(〃`l _ l´)ゞ☆

**Comment by mattn** [comment]
![](http://www.publicdomainpictures.net/pictures/50000/nahled/thumb-up-silhouette.jpg)

**Comment by raa0121** [comment]
@ujihisa sugoicraft とか cloft はujm のほうが詳しいかもしれないので、あれだったら執筆お願いします

**Comment by ujihisa** [comment]
@raa0121 
![](https://camo.githubusercontent.com/0afea92977ac3abe2a12cd4a37590ddabc9a7111/687474703a2f2f7777772e7075626c6963646f6d61696e70696374757265732e6e65742f70696374757265732f35303030302f6e61686c65642f7468756d622d75702d73696c686f75657474652e6a7067)

**Comment by ujihisa** [comment]
指でかいw
